-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."recipe_ingredients" add column "needs_preparation" boolean
--  not null default 'false';
