version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend@sha256:ed6d85c3a34e47d44e4db6baeb0563afa23b4aebb65b03dc88f0b91ff4e702e5
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  backend:
    image: ghcr.io/cookwherever/backend@sha256:dd218a5e05181abfca5cdf61ac26164f09b5d2bcd504b0e28e20042fef63ba4b
    restart: always
    environment:
      PORT: 80
      WASP_WEB_CLIENT_URL: https://cookwherever.com
    env_file:
      - .env.prod.secrets
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  wiki:
    image: ghcr.io/cookwherever/wiki@sha256:c161954d8912b232a2b0fa89a0624ab1a272f45e6efd10f2dc679749ce614859
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
