version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend@sha256:bde07928a0612a5e186deac302ed960032dea531a527867744e41fce633f1571
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.service.expose: "recipes.cookwherever.com"
      kompose.service.expose.tls-secret: "cookwherever-com-tls"
      kompose.image-pull-secret: "ghcr-pull-secret"
  wiki:
    image: ghcr.io/cookwherever/wiki@sha256:d6e31a79d71f3fbdf3b168d6d76d3c0decfa3495cff436eb55432a056bd44bbe
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.service.expose: "cookwherever.com"
      kompose.service.expose.tls-secret: "cookwherever-com-tls"
      kompose.image-pull-secret: "ghcr-pull-secret"
  hasura-auth:
    environment:
      AUTH_SERVER_URL: https://login.cookwherever.com
      AUTH_CLIENT_URL: https://cookwherever.com
    env_file:
      - .env.prod.secrets
  graphql-engine:
    image: hasura/graphql-engine:v2.4.0
    # image: ghcr.io/cookwherever/hasura:latest
    env_file:
      - .env
      - .env.prod.secrets
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
