services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
