version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend@sha256:414944011aae1a78906338aa7dcffd6391f0004d81ab226fcb214c6dc08c3c08
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  wiki:
    image: ghcr.io/cookwherever/wiki@sha256:c161954d8912b232a2b0fa89a0624ab1a272f45e6efd10f2dc679749ce614859
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  kratos:
    command: serve -c /config/kratos/config.yaml -c /config/kratos/config.production.yaml
    env_file:
      - .env.prod.secrets
  oathkeeper:
    env_file:
      - .env
      - .env.prod
  graphql-engine:
    image: hasura/graphql-engine:v2.9.0
    # image: ghcr.io/cookwherever/hasura:latest
    env_file:
      - .env
      - .env.prod.secrets
