version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend@sha256:d1bee2517a58cbbf04588d3c5f1d39249c9062b55cb46943204bf2bb366070cd
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  backend:
    image: ghcr.io/cookwherever/backend@sha256:9584569462c3b1be40e5a293d738014e67e8122828e73bfc7bd58d8b764db265
    restart: always
    environment:
      PORT: 80
      WASP_WEB_CLIENT_URL: https://cookwherever.com
    env_file:
      - .env.prod.secrets
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  wiki:
    image: ghcr.io/cookwherever/wiki@sha256:c161954d8912b232a2b0fa89a0624ab1a272f45e6efd10f2dc679749ce614859
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
