version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.9.0
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.3
    environment:
      - DSN=postgres://postgres:secretpgpassword@postgres:5432/cookwherever
    command: -c /config/kratos/config.yaml migrate sql -e --yes
    restart: on-failure
    volumes:
      - ./ory/kratos:/config/kratos
    depends_on:
      - postgres
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.9.0-alpha.3
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      DSN: postgres://postgres:secretpgpassword@postgres:5432/cookwherever
      LOG_LEVEL: trace
      SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_MAPPER_URL: file:///config/kratos/oidc.google.jsonnet
    command: serve -c /config/kratos/config.yaml -c /config/kratos/config.dev.yaml --dev --watch-courier
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./ory/kratos:/config/kratos
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
  oathkeeper:
    image: oryd/oathkeeper:v0.38
    ports:
      - "4455:4455"
      - "4456:4456"
    command: '--config /config/oathkeeper/config.yaml serve'
    environment:
      ACCESS_RULES_REPOSITORIES: file:///config/oathkeeper/rules.yaml,file:///config/oathkeeper/rules.frontend.yaml
      MUTATORS_ID_TOKEN_CONFIG_JWKS_URL: file:///config/oathkeeper/jwks.json
    volumes:
      - "./ory/oathkeeper:/config/oathkeeper"
    extra_hosts:
      - "host.docker.internal:host-gateway"