version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend@sha256:3c9430f064a9c3fe4f491dc4b5bd1d57923bfeb861f7cd2264929fd0cbda3004
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.service.expose: "recipes.cookwherever.com"
      kompose.service.expose.tls-secret: "cookwherever-com-tls"
      kompose.image-pull-secret: "ghcr-pull-secret"
  wiki:
    image: ghcr.io/cookwherever/wiki@sha256:baf8476d72e3480c8ba729c52a45a08f08abf9b74c6a712c8504d42f8f54b0fa
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.service.expose: "cookwherever.com"
      kompose.service.expose.tls-secret: "cookwherever-com-tls"
      kompose.image-pull-secret: "ghcr-pull-secret"
  hasura-auth:
    environment:
      AUTH_SERVER_URL: https://login.cookwherever.com
      AUTH_CLIENT_URL: https://cookwherever.com
      AUTH_PROVIDER_GOOGLE_CLIENT_ID: 875893625137-o31bbtcuu3qvou8l617hkd35letm8451.apps.googleusercontent.com
      AUTH_PROVIDER_GOOGLE_CLIENT_SECRET: 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
  graphql-engine:
    image: hasura/graphql-engine:v2.4.0
    # image: ghcr.io/cookwherever/hasura:latest
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
