version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend@sha256:46da6de146428b71d24237f2c4b2d96dc0d660c4c48d15c51993a09b594fedc8
    # image: ghcr.io/cookwherever/frontend:latest
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.service.expose: "cookwherever.com"
      kompose.service.expose.tls-secret: "cookwherever-com-tls"
      kompose.image-pull-secret: "ghcr-pull-secret"
  hasura-auth:
    environment:
      AUTH_SERVER_URL: https://login.cookwherever.com
      AUTH_CLIENT_URL: https://cookwherever.com
      AUTH_PROVIDER_GOOGLE_CLIENT_ID: 875893625137-o31bbtcuu3qvou8l617hkd35letm8451.apps.googleusercontent.com
      AUTH_PROVIDER_GOOGLE_CLIENT_SECRET: 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
  graphql-engine:
    image: hasura/graphql-engine:v2.4.0
    # image: ghcr.io/cookwherever/hasura:latest
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
