version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend@sha256:f53b2ffd6fd4c12f0fa19b6d8454adbc294b794017db96e7ad445dca22fc1329
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  wiki:
    image: ghcr.io/cookwherever/wiki@sha256:9c91ba3c843b4bf9c543e57964a2a8d02253be6afe451a339edb7950ebaa6705
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  kratos:
    env_file:
      - .env.prod.secrets
  oathkeeper:
    env_file:
      - .env
      - .env.prod
  graphql-engine:
    image: hasura/graphql-engine:v2.9.0
    # image: ghcr.io/cookwherever/hasura:latest
    env_file:
      - .env
      - .env.prod.secrets
