version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend@sha256:4d86fa74e543b4fdba8e394535af3a9650e73bca759c5350900f831f279efb73
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  backend:
    image: ghcr.io/cookwherever/backend@sha256:44c40cd93659fd4e25492a42e167738f3fa2cfd48f4f9342852b33454a2ba8d1
    restart: always
    environment:
      PORT: 80
      WASP_WEB_CLIENT_URL: https://cookwherever.com
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  wiki:
    image: ghcr.io/cookwherever/wiki@sha256:c161954d8912b232a2b0fa89a0624ab1a272f45e6efd10f2dc679749ce614859
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
