version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.9.0
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
  hasura-auth:
    image: nhost/hasura-auth:0.9.3
    depends_on:
      - postgres
      - graphql-engine
    env_file:
      - .env
    volumes:
      - ./hasura-auth/migrations:/app/migrations
    ports:
      - '4000:4000'
  mailhog:
    image: mailhog/mailhog
    env_file:
      - .env
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    volumes:
      - ./docker/data/mailhog:/maildir
