version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend@sha256:703f00f7890f819ded18188cf6e8509244768a51eb741e6d9792a438e24502d1
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  backend:
    image: ghcr.io/cookwherever/backend@sha256:3df663f9fb6cab039887a5e82356fd4d12618883cddb1d0973874c7f716b7b31
    restart: always
    environment:
      PORT: 80
      WASP_WEB_CLIENT_URL: https://cookwherever.com
    env_file:
      - .env.prod.secrets
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
  wiki:
    image: ghcr.io/cookwherever/wiki@sha256:c161954d8912b232a2b0fa89a0624ab1a272f45e6efd10f2dc679749ce614859
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.image-pull-secret: "ghcr-pull-secret"
