version: '3.6'
services:
  frontend:
    image: ghcr.io/cookwherever/frontend:v0.0.42
    restart: always
    ports:
      - '80:80'
    labels: 
      kompose.image-pull-secret: "ghcr-pull-secret"
  wiki:
    image: ghcr.io/cookwherever/wiki:latest
    restart: always
    ports:
      - '80:80'
    labels: 
      kompose.image-pull-secret: "ghcr-pull-secret"
  hasura-auth:
    environment:
      AUTH_SERVER_URL: https://login.cookwherever.com
      AUTH_CLIENT_URL: https://cookwherever.com
    env_file:
      - .env.prod.secrets
  graphql-engine:
    image: hasura/graphql-engine:v2.9.0
    # image: ghcr.io/cookwherever/hasura:latest
    env_file:
      - .env
      - .env.prod.secrets
