version: '3.6'
services:
  frontend:
    image: cthompson4321/fooddata-frontend:v0.0.11
    restart: always
    ports:
      - '80:80'
    labels:
      kompose.service.expose: "cookwherever.com"
      kompose.service.expose.tls-secret: "cookwherever-com-tls"
  hasura-auth:
    environment:
      AUTH_SERVER_URL: https://login.cookwherever.com
      AUTH_CLIENT_URL: https://cookwherever.com
      AUTH_PROVIDER_GOOGLE_CLIENT_ID: 875893625137-o31bbtcuu3qvou8l617hkd35letm8451.apps.googleusercontent.com
      AUTH_PROVIDER_GOOGLE_CLIENT_SECRET: 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
