# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1c\n\x0cParseRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"-\n\rParseResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t2<\n\x10IngredientParser\x12(\n\x05Parse\x12\r.ParseRequest\x1a\x0e.ParseResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARSEREQUEST._serialized_start=17
  _PARSEREQUEST._serialized_end=45
  _PARSERESPONSE._serialized_start=47
  _PARSERESPONSE._serialized_end=92
  _INGREDIENTPARSER._serialized_start=94
  _INGREDIENTPARSER._serialized_end=154
# @@protoc_insertion_point(module_scope)
