-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."recipe_directions" add column "video_timestamp" integer
--  null;
