# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1a\n\nIngredient\x12\x0c\n\x04name\x18\x01 \x01(\t\"G\n\x15ParseDirectionRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12 \n\x0bingredients\x18\x02 \x03(\x0b\x32\x0b.Ingredient\"6\n\x16ParseDirectionResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t2M\n\x06Parser\x12\x43\n\x0eParseDirection\x12\x16.ParseDirectionRequest\x1a\x17.ParseDirectionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INGREDIENT._serialized_start=17
  _INGREDIENT._serialized_end=43
  _PARSEDIRECTIONREQUEST._serialized_start=45
  _PARSEDIRECTIONREQUEST._serialized_end=116
  _PARSEDIRECTIONRESPONSE._serialized_start=118
  _PARSEDIRECTIONRESPONSE._serialized_end=172
  _PARSER._serialized_start=174
  _PARSER._serialized_end=251
# @@protoc_insertion_point(module_scope)
