-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW most_common_ingredients AS SELECT name, count(*) as ingredient_count FROM recipe_ingredients GROUP BY name ORDER BY ingredient_count DESC;
