serve:
  public:
    base_url: https://cookwherever.com/api/kratos/
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: https://cookwherever.com/
  allowed_return_urls:
    - https://cookwherever.com

  flows:
    error:
      ui_url: https://cookwherever.com/auth/error

    settings:
      ui_url: https://cookwherever.com/api/kratos/settings

    recovery:
      ui_url: https://cookwherever.com/api/kratos/recovery

    verification:
      ui_url: https://cookwherever.com/api/kratos/verification
      after:
        default_browser_return_url: https://cookwherever.com/

    logout:
      after:
        default_browser_return_url: https://cookwherever.com

    login:
      ui_url: https://cookwherever.com
      lifespan: 10m
      after:
        oidc:
          hooks:
            - hook: web_hook
              config:
                url: http://localhost:3002/github/login
                method: POST
                body: file:///config/oidc.hook.jsonnet

    registration:
      ui_url: https://cookwherever.com/
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session
            - hook: web_hook
              config:
                url: http://localhost:3002/github/login
                method: POST
                body: file:///config/oidc.hook.jsonnet

log:
  level: debug
  format: text
  leak_sensitive_values: false

