apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert -c -o k8s
    kompose.service.expose: fooddata-login.vanderpot.net
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: hasura-auth
  name: hasura-auth
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: hasura-auth
status:
  loadBalancer: {}
