-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."recipe_sources" add column "enum_id" integer
--  not null unique;
