apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cookwherever-com
  namespace: food-data
spec:
  secretName: cookwherever-com-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - cookwherever.com
    - '*.cookwherever.com'