apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yaml -f docker-compose.prod.yaml convert -c -o k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: graphql-engine
  name: graphql-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: graphql-engine
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.yaml -f docker-compose.prod.yaml convert -c -o k8s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: graphql-engine
    spec:
      containers:
        - env:
            - name: ALL_YES
              valueFrom:
                configMapKeyRef:
                  key: ALL_YES
                  name: env
            - name: AUTH_PROVIDER_GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: AUTH_PROVIDER_GOOGLE_CLIENT_ID
                  name: env-prod-secrets
            - name: AUTH_PROVIDER_GOOGLE_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: AUTH_PROVIDER_GOOGLE_CLIENT_SECRET
                  name: env-prod-secrets
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                configMapKeyRef:
                  key: HASURA_GRAPHQL_ADMIN_SECRET
                  name: env-prod-secrets
            - name: HASURA_GRAPHQL_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: HASURA_GRAPHQL_DATABASE_URL
                  name: env-prod-secrets
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              valueFrom:
                configMapKeyRef:
                  key: HASURA_GRAPHQL_ENABLE_CONSOLE
                  name: env
            - name: HASURA_GRAPHQL_GRAPHQL_URL
              valueFrom:
                configMapKeyRef:
                  key: HASURA_GRAPHQL_GRAPHQL_URL
                  name: env
            - name: HASURA_GRAPHQL_JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: HASURA_GRAPHQL_JWT_SECRET
                  name: env-prod-secrets
            - name: HASURA_GRAPHQL_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: HASURA_GRAPHQL_LOG_LEVEL
                  name: env
            - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
              valueFrom:
                configMapKeyRef:
                  key: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
                  name: env
            - name: NO_INQUIRY
              valueFrom:
                configMapKeyRef:
                  key: NO_INQUIRY
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-prod-secrets
            - name: TRUST_PROXY_HEADER
              valueFrom:
                configMapKeyRef:
                  key: TRUST_PROXY_HEADER
                  name: env
          image: hasura/graphql-engine:v2.9.0
          name: graphql-engine
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
