apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yaml -f docker-compose.prod.yaml convert -c -o k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: kratos
  name: kratos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kratos
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.yaml -f docker-compose.prod.yaml convert -c -o k8s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: kratos
    spec:
      containers:
        - args:
            - serve
            - -c
            - /config/kratos/config.yaml
            - -c
            - /config/kratos/config.dev.yaml
            - --dev
            - --watch-courier
          env:
            - name: DSN
              value: postgres://postgres:secretpgpassword@postgres:5432/cookwherever
            - name: LOG_LEVEL
              value: trace
            - name: SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_MAPPER_URL
              value: file:///config/kratos/oidc.google.jsonnet
          image: oryd/kratos:v0.9.0-alpha.3
          name: kratos
          ports:
            - containerPort: 4433
            - containerPort: 4434
          resources: {}
          volumeMounts:
            - mountPath: /config/kratos
              name: kratos-claim0
      restartPolicy: Always
      volumes:
        - name: kratos-claim0
          persistentVolumeClaim:
            claimName: kratos-claim0
status: {}
