apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.yaml -f docker-compose.prod.yaml convert -c -o k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: oathkeeper
  name: oathkeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oathkeeper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.yaml -f docker-compose.prod.yaml convert -c -o k8s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: oathkeeper
    spec:
      containers:
        - args:
            - --config
            - /config/oathkeeper/config.yaml
            - serve
          env:
            - name: ACCESS_RULES_REPOSITORIES
              value: file:///config/oathkeeper/rules.yaml,file:///config/oathkeeper/rules.frontend.yaml
            - name: MUTATORS_ID_TOKEN_CONFIG_JWKS_URL
              value: file:///config/oathkeeper/jwks.json
          image: oryd/oathkeeper:v0.38
          name: oathkeeper
          ports:
            - containerPort: 4455
            - containerPort: 4456
          resources: {}
          volumeMounts:
            - mountPath: /config/oathkeeper
              name: oathkeeper-claim0
      restartPolicy: Always
      volumes:
        - name: oathkeeper-claim0
          persistentVolumeClaim:
            claimName: oathkeeper-claim0
status: {}
