serve:
  proxy:
    port: 4455 # run the proxy at port 4455
  api:
    port: 4456 # run the api at port 4456

access_rules:
  repositories:
    - file://rules.yaml

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  noop:
    enabled: true

  hydrator:
    enabled: true
    config:
      api:
        url: http://host.docker.internal:8088/oathkeeper/hydrate

  id_token:
    enabled: true
    config:
      issuer_url: http://oathkeeper:4455/
      jwks_url: file://jwks.json
      claims: |
        {
          "https://hasura.io/jwt/claims": {
            {{ if .Extra.user_id }}
              "x-hasura-user-id": "{{ .Extra.user_id }}",
              "x-hasura-allowed-roles": ["user"],
              "x-hasura-default-role": "user"
            {{ else }}
              "x-hasura-allowed-roles": ["anonymous"],
              "x-hasura-default-role": "anonymous"
            {{ end }}
          }
        }

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  anonymous:
    enabled: true
    config:
      subject: 73324cc4-951c-4756-aa95-872b9cd6c0e5

  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session
