export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const SET_CURRENT_PROPERTY = 'SET_CURRENT_PROPERTY';
export const SET_SOURCE = 'SET_SOURCE';
export const OBJECTS_SELECTED = 'OBJECTS_SELECTED';
export const NEXT_PROPERTY = 'NEXT_PROPERTY';
export const RECIPES_SCRAPED = 'RECIPES_SCRAPED';