name: Hasura

on:
  workflow_dispatch:
  push:
    paths:
      - 'hasura/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - run: |
          cd hasura
          docker build . --file Dockerfile --tag build
        name: "Build image"

      - name: Log into registry
        if: steps.branch-name.outputs.current_branch == 'master'
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: steps.branch-name.outputs.current_branch == 'master'
        run: |
          IMAGE_ID=ghcr.io/cookwherever/hasura
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag build $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
        
          sed -ie "s|$IMAGE_ID:(.+)|$IMAGE_ID:$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_ID:$VERSION)|" docker-compose.prod.yaml

      - name: Create commit
        id: create-commit
        if: steps.branch-name.outputs.current_branch == 'master'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docker-compose.prod.yaml
          commit_message: "chore: update container hash [skip ci]"
          commit_user_name: cookwherever[bot]
          commit_user_email: cookwherever[bot]@users.noreply.github.com
          commit_author: cookwherever[bot] <cookwherever[bot]@users.noreply.github.com>
      - name: Save commit hash
        id: save-commit-hash
        run: |
          if [ "${{ steps.create-commit.outputs.changes_detected || 'unknown' }}" == "true" ]; then
            echo '::set-output name=commit_hash::${{ steps.create-commit.outputs.commit_hash }}'
          else
            echo "::set-output name=commit_hash::${GITHUB_SHA}"
          fi
      - name: Invoke deploy on new commit
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ steps.create-commit.outputs.commit_hash }}

